//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfTestClientConsole.GymWorkoutService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FlattenWorkout", Namespace="http://schemas.datacontract.org/2004/07/Dto")]
    [System.SerializableAttribute()]
    public partial class FlattenWorkout : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GoalDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UniqueIdentifierField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((this.EndTimeField.Equals(value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GoalDescription {
            get {
                return this.GoalDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.GoalDescriptionField, value) != true)) {
                    this.GoalDescriptionField = value;
                    this.RaisePropertyChanged("GoalDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UniqueIdentifier {
            get {
                return this.UniqueIdentifierField;
            }
            set {
                if ((this.UniqueIdentifierField.Equals(value) != true)) {
                    this.UniqueIdentifierField = value;
                    this.RaisePropertyChanged("UniqueIdentifier");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GymWorkoutService.IWorkoutService")]
    public interface IWorkoutService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkoutService/GetAllWorkout", ReplyAction="http://tempuri.org/IWorkoutService/GetAllWorkoutResponse")]
        System.Collections.Generic.List<WcfTestClientConsole.GymWorkoutService.FlattenWorkout> GetAllWorkout();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkoutService/GetAllWorkout", ReplyAction="http://tempuri.org/IWorkoutService/GetAllWorkoutResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WcfTestClientConsole.GymWorkoutService.FlattenWorkout>> GetAllWorkoutAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkoutService/GetWorkout", ReplyAction="http://tempuri.org/IWorkoutService/GetWorkoutResponse")]
        WcfTestClientConsole.GymWorkoutService.FlattenWorkout GetWorkout(int uniqueIdentifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkoutService/GetWorkout", ReplyAction="http://tempuri.org/IWorkoutService/GetWorkoutResponse")]
        System.Threading.Tasks.Task<WcfTestClientConsole.GymWorkoutService.FlattenWorkout> GetWorkoutAsync(int uniqueIdentifier);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWorkoutServiceChannel : WcfTestClientConsole.GymWorkoutService.IWorkoutService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WorkoutServiceClient : System.ServiceModel.ClientBase<WcfTestClientConsole.GymWorkoutService.IWorkoutService>, WcfTestClientConsole.GymWorkoutService.IWorkoutService {
        
        public WorkoutServiceClient() {
        }
        
        public WorkoutServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WorkoutServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorkoutServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorkoutServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<WcfTestClientConsole.GymWorkoutService.FlattenWorkout> GetAllWorkout() {
            return base.Channel.GetAllWorkout();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WcfTestClientConsole.GymWorkoutService.FlattenWorkout>> GetAllWorkoutAsync() {
            return base.Channel.GetAllWorkoutAsync();
        }
        
        public WcfTestClientConsole.GymWorkoutService.FlattenWorkout GetWorkout(int uniqueIdentifier) {
            return base.Channel.GetWorkout(uniqueIdentifier);
        }
        
        public System.Threading.Tasks.Task<WcfTestClientConsole.GymWorkoutService.FlattenWorkout> GetWorkoutAsync(int uniqueIdentifier) {
            return base.Channel.GetWorkoutAsync(uniqueIdentifier);
        }
    }
}
